const LABEL = {
  onset: "Monsoon Onset",
  break: "Monsoon Break",
  revival: "Revival",
  dry_spell: "Dry Spell",
};

export default function Advisory({ forecast, explanation, advisory }) {
  if (!explanation) {
    return (
      <section className="panel">
        <h2>Advisory</h2>
        <p className="muted">No advisory is available for this selection.</p>
      </section>
    );
  }

  const isGroq = explanation.source === "groq";
  const dom = explanation.dominant_state ?? advisory?.dominant_state;
  const domCard = (advisory?.items ?? []).find((c) => c.state === dom);
  const domLabel = LABEL[dom] ?? dom;
  const domPct = domCard
    ? `${domCard.probability_pct?.toFixed?.(1) ?? Number(domCard.probability_pct) ?? "—"}%`
    : null;

  return (
    <section className="panel">
      <h2>Advisory</h2>

      <div className="dominant-callout" data-testid="dominant-callout">
        <span className="callout-tag">Dominant signal</span>
        <span>
          <strong>{domLabel}</strong>
          {domPct ? ` — ${domPct} probability` : ""}
        </span>
        <span className="source-badge" data-testid="advisory-source">
          {isGroq ? (
            <>
              <span className="dot-green" /> Groq explanation
            </>
          ) : (
            <>
              <span className="dot-gray" /> Deterministic advisory
            </>
          )}
        </span>
      </div>
      {explanation.groq?.status === "not_configured" && (
        <p className="notice">
          Groq is not configured on the backend; the deterministic advisory is shown.
        </p>
      )}
      {explanation.groq?.status === "error" && (
        <p className="notice">
          Groq was unavailable, so the deterministic advisory is shown (
          {explanation.groq.note}).
        </p>
      )}
      {isGroq && explanation.groq?.model && (
        <p className="muted">Generated by {explanation.groq.model} from frozen model output.</p>
      )}

      <div className="advisory-blocks">
        <div className="adv-block">
          <h3>What is happening?</h3>
          <p>{explanation.summary}</p>
        </div>
        <div className="adv-block">
          <h3>What does it mean?</h3>
          <p>{explanation.why}</p>
        </div>
        <div className="adv-block">
          <h3>What should the user consider?</h3>
          <p>{explanation.action}</p>
        </div>
        <div className="adv-block adv-caution">
          <h3>Caution</h3>
          <p>{explanation.caution}</p>
        </div>
      </div>
    </section>
  );
}