import React from 'react';

export default function PrintableAdvisory({ forecast, decision, village, onClose }) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, 
      backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 9999,
      display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px'
    }}>
      <div className="glass-panel printable-area" style={{ 
        background: '#fff', width: '100%', maxWidth: '700px', maxHeight: '90vh', overflowY: 'auto',
        color: '#000', padding: '40px', borderRadius: '12px', boxShadow: '0 10px 25px rgba(0,0,0,0.2)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}>
          <h1 style={{ margin: 0, fontSize: '24px', color: '#000', borderBottom: '2px solid #000', paddingBottom: '10px' }}>
            OFFICIAL AGRICULTURAL ADVISORY
          </h1>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '16px' }} className="no-print">✕</button>
        </div>
        
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '30px' }}>
          <div>
            <p><strong>Location:</strong> {village?.name_en || 'Cuddalore'} ({village?.name_ta || 'கடலூர்'})</p>
            <p><strong>Date Issued:</strong> {new Date().toLocaleDateString()}</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p><strong>Generated By:</strong> SIH Monsoon Intelligence System</p>
          </div>
        </div>

        <div style={{ background: '#f5f5f5', padding: '20px', borderRadius: '8px', marginBottom: '30px', borderLeft: '4px solid #000' }}>
          <h2 style={{ margin: '0 0 10px 0', fontSize: '18px' }}>MONSOON STATUS: {forecast?.prediction?.status?.toUpperCase() || 'LIKELY'}</h2>
          <p style={{ margin: 0, fontSize: '16px' }}><strong>RECOMMENDED ACTION:</strong> {decision?.action || 'WAIT BEFORE SOWING'}</p>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h3 style={{ fontSize: '16px', borderBottom: '1px solid #ccc', paddingBottom: '5px' }}>Advisory Message / செய்தி / संदेश</h3>
          <p style={{ fontSize: '16px', lineHeight: '1.6' }}>
            <strong>English:</strong> Monsoon onset conditions are currently evaluated as {forecast?.prediction?.status || 'Likely'}. 
            Based on current soil and rainfall predictions, the recommended action for farmers in this block is to {decision?.action || 'WAIT'}.
          </p>
          <p style={{ fontSize: '16px', lineHeight: '1.6', marginTop: '15px' }}>
            <strong>தமிழ்:</strong> பருவமழை நிலை தற்போது {forecast?.prediction?.status || 'சாத்தியம்'} என மதிப்பிடப்பட்டுள்ளது. 
            தற்போதைய மண் மற்றும் மழையளவின் அடிப்படையில், இந்தப்பகுதி விவசாயிகள் விதைப்பை {decision?.action === 'WAIT' ? 'தள்ளிப்போடவும்' : 'தொடங்கவும்'} என அறிவுறுத்தப்படுகிறது.
          </p>
          <p style={{ fontSize: '16px', lineHeight: '1.6', marginTop: '15px' }}>
            <strong>हिंदी:</strong> मानसून की स्थिति वर्तमान में {forecast?.prediction?.status || 'संभावित'} है। 
            मिट्टी और बारिश की भविष्यवाणियों के आधार पर, किसानों के लिए अनुशंसित कार्रवाई है: {decision?.action || 'WAIT'}।
          </p>
        </div>

        <div style={{ fontSize: '12px', color: '#666', borderTop: '1px solid #eee', paddingTop: '20px' }}>
          <strong>DATA PROVENANCE:</strong><br/>
          Source: {forecast?.provenance?.source || 'IMD Grid'}<br/>
          Model: {forecast?.provenance?.model_version || 'FREEZE_H'}<br/>
          Generated: {forecast?.generated_at || 'N/A'}<br/>
          Mode: {forecast?.mode === 'live' ? 'LIVE' : forecast?.mode === 'demo' ? 'DEMO' : 'OFFLINE'}<br/><br/>
          Advisory generated from the Agricultural Monsoon Intelligence System.<br/>
          Please follow local agricultural department recommendations and field conditions.
        </div>

        <div className="no-print" style={{ textAlign: 'center', marginTop: '20px', borderTop: '1px solid #eee', paddingTop: '20px' }}>
          <button onClick={handlePrint} style={{ 
            padding: '10px 24px', background: '#000', color: '#fff', 
            border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold' 
          }}>
            Print Notice
          </button>
        </div>

        <style>{`
          @media print {
            body * { visibility: hidden; }
            .printable-area, .printable-area * { visibility: visible; }
            .printable-area { position: absolute; left: 0; top: 0; width: 100%; box-shadow: none; }
            .no-print { display: none !important; }
          }
        `}</style>
      </div>
    </div>
  );
}
